### ISSUE TITLE
Input File Open Failed

### ISSUE THREAD

**Issue by jjgiesey** [Milligan-Engineering/SolarSysSpecif#6]
When I went to run your program I got a failure to open the input. (Good job including a fail procedure.) Since the data file has not been created yet I get an error. The second time someone runs the program it would be OK since the output creates a file.

**Comment by efforgety** [comment]
I have made some modifications to the program to try and correct this error. I added a switch menu so that you could write data to the file in case 1 before reading that data on the second run to do an analysis in case 2. However, even after I run case 1, when I try to do case 2, I get an input file open error. I'm assuming my attempt to write to the file in case 1 failed, but I don't know why. Can you please give my latest commit to PM08Eval a look for any major errors and perhaps give me some tips?

**Comment by jjgiesey** [comment]
Fixed
